import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>IP Geocoder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my IP Geocoder!
        </h1>

        <p className={styles.description}>
          Enter an IP to get the latitude and longitude.
        </p>

        <Form />
      </main>
    </div>
  )
}

function Form() {
  const geocodeIp = async event => {
    event.preventDefault()

    const res = await fetch('/api/geocodeIp', {
      body: JSON.stringify({
        ip_address: event.target.ip_address.value
      }),
      headers: {
        'Content-Type': 'application/json'
      },
      method: 'POST'
    })

    const result = await res.json()
    console.log("result: " + JSON.stringify(result));
  }

  return (
    <form onSubmit={geocodeIp}>
      <label htmlFor="ip_address">IP Address:</label>
      <input id="ip_address" name="ip_address" type="text" required />
      <button type="submit">Submit</button>
    </form>
  )
}
