import Head from 'next/head'
import Form from './form'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>IP Geocoder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my IP Geocoder!
        </h1>

        <p className={styles.description}>
          Enter an IP to get the latitude and longitude.
        </p>

        <Form />
      </main>
    </div>
  )
}
